name: flutter_contact_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/contact.png
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 700
        - asset: assets/font/Poppins-Regular.ttf
          weight: 500
        - asset: assets/font/Poppins-Light.ttf
          weight: 300